// <auto-generated />
namespace HealthCareWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class model11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(model11));
        
        string IMigrationMetadata.Id
        {
            get { return "201512081942116_model11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
